from tkinter import *
win = Tk()
win.geometry("400x400")
win.title("Tai khoan")
lab1 = Label(win, text="Doi mat khau")
lab2 = Label(win, text="Ten dang nhap")
ent1 = Entry(win, width=20)
lab3 = Label(win, text="Mật khẩu cũ")
ent2 = Entry(win, width=20)
lab4 = Label(win, text="Mật khẩu mới")
ent3 = Entry(win, width=20)
lab5 = Label(win, text="Nhập lại mật khẩu mới")
ent4 = Entry(win, width=20)
btn1 = Button(win, text="Đồng ý")
btn2 =Button(win, text="Thoát", command=win.destroy())
lab1.pack()
lab2.pack(ipadx=200, ipady=150)
ent1.pack(ipadx=300, ipady=150)
win.mainloop()